### ISSUE TITLE
SL Micro 6 requires EIB 1.1

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/atip#14]
https://github.com/suse-edge/atip/blob/e821cc538ca4d6b1f46a59e0723b95d2c7bb3637/telco-examples/mgmt-cluster/multi-node/eib/mgmt-cluster-multinode.yaml#L1 https://github.com/suse-edge/edge-image-builder/blob/main/RELEASE_NOTES.md#general-1

**Comment by atanasdinov** [comment]
`apiVersion` has nothing to do with EIB version - EIB v1.1 supports `apiVersion: 1.0`.

**Comment by e-minguez** [comment]
ack, so it is only for fips mode I guess.
